version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes: 
      - ${PWD}/db:/var/lib/postgresql/data
    networks:
      - db
networks:
  db: