# Generated by Django 4.2.4 on 2023-08-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationModel',
            new_name='UsersModel',
        ),
    ]
