# Generated by Django 4.2.4 on 2023-08-31 07:37

import django.contrib.auth.password_validation
from django.db import migrations, models
import users_reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_reports', '0002_rename_registrationmodel_usersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='confirm_password',
            field=models.CharField(default=None, max_length=50, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='email',
            field=models.EmailField(default=None, max_length=100, validators=[users_reports.models.validate_3insys_email]),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='password',
            field=models.CharField(default=None, max_length=50, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='security_question1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='security_question2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='security_question3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
