# Generated by Django 4.2.4 on 2023-09-01 06:14

import django.contrib.auth.password_validation
from django.db import migrations, models
import users_reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_reports', '0003_usersmodel_confirm_password_alter_usersmodel_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmodel',
            old_name='security_question1',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='usersmodel',
            old_name='security_question2',
            new_name='answer2',
        ),
        migrations.RenameField(
            model_name='usersmodel',
            old_name='security_question3',
            new_name='answer3',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='question1',
            field=models.CharField(choices=[('In what city were you born', 'In what city were you born'), ('What is the name of your favorite pet?', 'What is the name of your favorite pet?'), ('What high school did you attend?', 'What high school did you attend?'), ('What was the make of your first car?', 'What was the make of your first car?'), ('Where did you meet your spouse?', 'Where did you meet your spouse?'), ('What year was your father (or mother) born?', 'What year was your father (or mother) born?')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='question2',
            field=models.CharField(choices=[('In what city were you born', 'In what city were you born'), ('What is the name of your favorite pet?', 'What is the name of your favorite pet?'), ('What high school did you attend?', 'What high school did you attend?'), ('What was the make of your first car?', 'What was the make of your first car?'), ('Where did you meet your spouse?', 'Where did you meet your spouse?'), ('What year was your father (or mother) born?', 'What year was your father (or mother) born?')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='question3',
            field=models.CharField(choices=[('In what city were you born', 'In what city were you born'), ('What is the name of your favorite pet?', 'What is the name of your favorite pet?'), ('What high school did you attend?', 'What high school did you attend?'), ('What was the make of your first car?', 'What was the make of your first car?'), ('Where did you meet your spouse?', 'Where did you meet your spouse?'), ('What year was your father (or mother) born?', 'What year was your father (or mother) born?')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True, validators=[users_reports.models.validate_3insys_email]),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='password',
            field=models.CharField(default=None, max_length=50, unique=True, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='username',
            field=models.CharField(default=None, max_length=50, validators=[users_reports.models.validate_3insys_username]),
        ),
    ]
